- name: install php-fpm 
  yum: name=php72-php-fpm state=latest enablerepo=remi,remi-php72

- name: config php-fpm.d/www.conf listen
  lineinfile:
    dest: /etc/opt/remi/php72/php-fpm.d/www.conf
    state: present
    regexp: "^listen = "
    line: "listen = 127.0.0.1:9000"
    backup: yes
  notify: reload php72-php-fpm

- name: config php-fpm.d/www.conf user,group
  lineinfile:
    dest: /etc/opt/remi/php72/php-fpm.d/www.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  notify: reload php72-php-fpm
  with_items:
  - regexp: '^;?listen.owner = '
    line: 'listen.owner = nginx'
  - regexp: '^;?listen.group = '
    line: 'listen.group = nginx'
  - regexp: '^user = '
    line: 'user = nginx'
  - regexp: '^group = '
    line: 'group = nginx'

- name: started php-fpm
  systemd: name=php72-php-fpm state=started

- name: enabled php-fpm
  systemd: name=php72-php-fpm enabled=yes
