- name: php component install
  yum: name={{ item }} state=latest enablerepo=remi,remi-php72
  with_items:
    - "{{ php_pkgs }}"

- name: config php.ini error_reporting
  lineinfile:
    dest: /etc/opt/remi/php72/php.ini
    state: present
    insertafter: "^;error_reporting"
    regexp: "^error_reporting"
    line: "error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT"
    validate: "php72 -c %s -m"
    backup: yes

- name: config php.ini timezone
  lineinfile:
    dest: /etc/opt/remi/php72/php.ini
    state: present
    insertafter: "^;date.timezone"
    regexp: "^date.timezone"
    line: "date.timezone = Asia/Tokyo"
    validate: "php72 -c %s -m"
    backup: yes

- name: config php.ini expose_php
  lineinfile:
    dest: /etc/opt/remi/php72/php.ini
    state: present
    insertafter: "^;expose_php"
    regexp: "^expose_php"
    line: "expose_php = Off"
    validate: "php72 -c %s -m"
    backup: yes
